### ISSUE TITLE
E: Package 'mongodb' has no installation candidate ERROR: Service 'vscode' failed to build: The command '/bin/sh -c apt-get update &&       apt-get -y install  curl &&       curl -sL https://deb.nodesource.com/setup_12.x | sudo  -E bash - &&       apt-get -y install nodejs &&       apt-get -y install dirmngr apt-transport-https lsb-release ca-certificates &&       apt-get -y install mongodb &&       rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

### ISSUE THREAD

**Issue by kaushal77** [codeasylums/FullStackTool_docker#1]
ERROR: Service 'vscode' failed to build: The command '/bin/sh -c apt-get update &&       apt-get -y install  curl &&       curl -sL https://deb.nodesource.com/setup_12.x | sudo  -E bash - &&       apt-get -y install nodejs &&       apt-get -y install dirmngr apt-transport-https lsb-release ca-certificates &&       apt-get -y install mongodb &&       rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by ishu-harsh** [comment]
Ohk I have pushed the new code its working here so please check it again... by pulling the new code

**Comment by ishu0824** [comment]
Ohk I have pushed the new code its working here so please check it again... by pulling the new code

**Comment by kaushal77** [comment]
everything is working.
